CREATE TABLE IF NOT EXISTS earthquakes (
	seismic_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_id VARCHAR(200),
	mag DECIMAL NOT NULL,
	place VARCHAR(300) NOT NULL,
	earthquake_time BIGINT,
	updated BIGINT,
	timezone INT,
	url VARCHAR(500),
	earthquake_detail VARCHAR(500),
	felt INT,
	cdi DECIMAL,
	mmi DECIMAL,
	alert VARCHAR(50),
	status VARCHAR(50),
	tsunami INT,
	sig INT,
	net VARCHAR(50),
	code VARCHAR(50),
	ids VARCHAR(100),
	sources VARCHAR(50),
	product_types VARCHAR(200),
	mag_nst INT,
	dmin DECIMAL,
	rms DECIMAL,
	gap DECIMAL,
	mag_type VARCHAR(50),
	seismic_type VARCHAR(50),
	long_lat POINT,
	seismic_depth DECIMAL
);